version: '2'
networks:
  pelias:
    driver: bridge
volumes:
  libpostaldata:
    driver: local
services:
  libpostal_baseimage:
    image: pelias/libpostal_baseimage
    container_name: pelias_libpostal_baseimage
  libpostal:
    image: pelias/go-whosonfirst-libpostal
    container_name: pelias_libpostal
    restart: always
    ports: [ "8080:8080" ]
    networks: [ "pelias" ]
  schema:
    image: pelias/schema:portland-synonyms
    container_name: pelias_schema
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "./synonyms/custom_name.txt:/code/pelias/schema/synonyms/custom_name.txt"
      - "./synonyms/custom_street.txt:/code/pelias/schema/synonyms/custom_street.txt"
  api:
    depends_on: [ "libpostal_baseimage" ]
    image: pelias/api:master
    container_name: pelias_api
    restart: always
    environment: [ "PORT=4000" ]
    ports: [ "4000:4000" ]
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "libpostaldata:/usr/share/libpostal"
  placeholder:
    image: pelias/placeholder
    container_name: pelias_placeholder
    restart: always
    environment: [ "PORT=4100" ]
    ports: [ "4100:4100" ]
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  whosonfirst:
    image: pelias/whosonfirst
    container_name: pelias_whosonfirst
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  openstreetmap:
    image: pelias/openstreetmap:airport_codes
    container_name: pelias_openstreetmap
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  openaddresses:
    image: pelias/openaddresses
    container_name: pelias_openaddresses
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  transit:
    image: pelias/transit:master
    container_name: pelias_transit
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  polylines:
    image: pelias/polylines
    container_name: pelias_polylines
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  interpolation:
    depends_on: [ "libpostal_baseimage" ]
    image: pelias/interpolation
    container_name: pelias_interpolation
    restart: always
    environment: [ "PORT=4300" ]
    ports: [ "4300:4300" ]
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "libpostaldata:/usr/share/libpostal"
      - "${DATA_DIR}:/data"
  pip:
    image: pelias/pip-service
    container_name: pelias_pip-service
    restart: always
    environment: [ "PORT=4200" ]
    ports: [ "4200:4200" ]
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  document-service:
    image: pelias/document-service
    container_name: pelias_document-service
    restart: always
    ports: [ "5000:5000" ]
    networks: [ "pelias" ]
    volumes:
      - "./pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  elasticsearch:
    image: pelias/elasticsearch
    container_name: pelias_elasticsearch
    restart: always
    ports: [ "9200:9200", "9300:9300" ]
    networks: [ "pelias" ]
    volumes:
      - "${DATA_DIR}/elasticsearch:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add: [ "IPC_LOCK" ]
